services:
  - type: web
    name: Xstro
    runtime: docker
    repo: https://github.com/AstroX11/Xstro
    plan: free
    envVars:
      - key: TIME_ZONE
        sync: false
      - key: WARN_COUNT
        sync: false
      - key: STICKER_PACK
        sync: false
      - key: BOT_INFO
        sync: false
      - key: SUDO
        sync: false
      - key: SESSION_ID
        sync: false
    region: oregon
    dockerContext: .
    dockerfilePath: ./Dockerfile
version: '1'
